title: Mario Parawan Nonog Jr.
#logo: /Users/mariononog/Desktop/DSC03684.jpeg
description: Business Analytics Graduate Student and Navy Veteran with a strong foundation in data analysis, statistical modeling,
and business intelligence. Experienced in using tools such as Excel and Python to analyze complex datasets and deliver
actionable insights. Proven ability to identify trends, streamline workflows, and support decision-making processes in
fast-paced environments. Adept at collaborating across teams to solve business challenges through data-driven
solutions. Committed to leveraging analytical skills to improve organizational performance and drive growth. 
skills include:
show_downloads: true
theme: jekyll-theme-minimal
